name = "puppeteer-mcp-worker"
main = "index.ts"
compatibility_date = "2024-06-26"
compatibility_flags = ["nodejs_compat"]

[vars]
BROWSER_SERVICE = "browserless"  # or "scrapingbee"

# Environment variables (set these using wrangler secret)
# BROWSERLESS_TOKEN = "your-browserless-token"
# SCRAPINGBEE_TOKEN = "your-scrapingbee-token"

# For development
[env.development]
vars = { BROWSER_SERVICE = "browserless" }

# For production
[env.production]
vars = { BROWSER_SERVICE = "browserless" }

# Enable Node.js compatibility for MCP SDK
node_compat = true

# Custom domain configuration
routes = [
  { pattern = "puppeteer.techsci.dev/*", zone_name = "techsci.dev" }
]

# GitHub integration compatible build settings
# Note: Build is handled automatically by Wrangler for TypeScript files
# For GitHub Actions, use: npm run build && npx wrangler deploy

# KV namespace for storing screenshots/logs (optional)
# [[kv_namespaces]]
# binding = "SCREENSHOTS"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"